### ISSUE TITLE
multiplanar view cropping 

### ISSUE THREAD

**Issue by hanayik** [hanayik/niivue#42]
@neurolabusc, PR #41 seems to have introduced a cropping of the canvas. This can be seen only in the axial plane of the multiplanar view. Does your browser show this as well?

<img width="623" alt="Capture" src="https://user-images.githubusercontent.com/5217720/109397711-f8d40380-792f-11eb-9329-03cf0a7d2f93.PNG">

**Comment by neurolabusc** [comment]
[line 522 ](https://github.com/hanayik/niivue/blob/84b8021fdc44b189d24ca1d66589ad3c44bd20a3/src/niivue.js#L522) should be changed from
```
draw2D(gl, [ltwh[0],ltwh[1]+hY, wX, hY], 0)
```
to read
```
draw2D(gl, [ltwh[0],ltwh[1]+hZ, wX, hY], 0);
```

Last PR was somewhat incomplete (still need to implement fonts).
