### ISSUE TITLE
Colorbar placement overlaps sagittal slices in new test image

### ISSUE THREAD

**Issue by hanayik** [hanayik/niivue#50]
The colorbar seems to be drawn on top of the last few rows of the sagittal slices in MP view. 

example image to demonstrate:

Put this in App.vue for volume URL
"https://openneuro.org/crn/datasets/ds002328/snapshots/1.0.0/files/sub-01:anat:sub-01_T1w.nii.gz"

screenshot

<img width="892" alt="Screenshot 2021-03-02 at 10 53 00" src="https://user-images.githubusercontent.com/5217720/109638429-eaf7cb80-7b45-11eb-8825-1be13bab4516.png">

**Comment by neurolabusc** [comment]
Fix by changing [line 547](https://github.com/hanayik/niivue/blob/3f4184450e9653a35e37c54d96c3c4df2bee8b53/src/niivue.js#L547)

```
drawColorbar(gl, [ltwh[0]+wX+margin, ltwh[1] + hY + margin, wY - margin - margin, hY * colorbarHeight]);
```
to read
```
drawColorbar(gl, [ltwh[0]+wX+margin, ltwh[1] + hZ + margin, wY - margin - margin, hY * colorbarHeight]);
```

The latest pull request demonstrates writing a multi-character string with descenders by writing the string `Syzygy`. You may want to delete that line, but if you maintain it, it should also be adjusted:
```
//demonstrate multi-character string with font descenders
drawTextBelow(gl, [ltwh[0]+wX + (0.5 * wY), ltwh[1] + hZ + margin + hY * colorbarHeight ], "Syzygy");
//draw colorbar (optional)
var margin = colorBarMargin * hY;
drawColorbar(gl, [ltwh[0]+wX+margin, ltwh[1] + hZ + margin, wY - margin - margin, hY * colorbarHeight]);
```
