### ISSUE TITLE
loading volume from external URL results in distorted data in viewer

### ISSUE THREAD

**Issue by hanayik** [hanayik/niivue#82]
- clone the `url-loader` branch
- start a niivue server `npm run serve`
- put this in the browser address bar: `http://localhost:8080/?urls=https://openneuro.org/crn/datasets/ds002328/snapshots/1.0.0/files/sub-01:anat:sub-01_T1w.nii.gz`
- loaded data appears roughly head shaped, but is clearly corrupted, or mishandled somehow

to load from an external URL the volume at the URL needs to be universally readable. Some servers have security blocks to disallow browsers to repeatedly download files (plus that's unusual behavior for a browser). OpenNeuro seems to have a very permissible server though. 

## screenshot of issue

![Screenshot 2021-03-15 at 11 49 17](https://user-images.githubusercontent.com/5217720/111149241-8b0d1600-8584-11eb-818c-7e33661df84a.png)

**Comment by neurolabusc** [comment]
Taylor, I think we want some logic to deal with images where `cal_min` and `cal_max` are not set in the NIfTI header. There are three solutions:

 1. Use the minimum and maximum values in the dataset: this solution can be poor if outlier voxels are present.
 2. Determine percentiles, set `cal_min` = 2% and `cal_max` = 98%. This is the approach AFNI and MRIcron use.
 3. Use FSL's [robust range](https://github.com/rordenlab/niimath/blob/331758459140db59290a794350d0ff3ad4c37b67/src/core32.c#L1215) algorithm, which works better than the percentile approach for thresholded images. This is the approach that FSLeyes and MRIcroGL use.

Remember to use approach 1 if the `intent_code` is labels (e.g. index based atlas). We also want to consider atlas colormaps.
