### ISSUE TITLE
Render mode can crash iPhone/iPad Safari

### ISSUE THREAD

**Issue by neurolabusc** [hanayik/niivue#83]
WebGL2 support is still `experimental` in Safari. The niivue render mode can crash Safari on iPad and iPhone. However, this issue is not observed on Safari and Safari Technical Preview for the ARM-based M1 Macs. For the moment, I suggest we defer to see if upcoming versions of Safari for iOS resolve this issue. However, we could alter the volume rendering shader to make it more similar to Metal to see if this resolves the issue.

**Comment by hanayik** [comment]
I have experienced this as well. Only an issue in render mode. It may be nice to just detect OS/device type and disable render mode until it is more robust. 

https://stackoverflow.com/questions/9038625/detect-if-device-is-ios
